### PR TITLE
Cron: Modify expression parts based on the start time

### PR DESCRIPTION
**Pull request by yhabteab**

### CODE REVIEW

**Comment by yhabteab** [comment]
After a long time of experimenting, I finally realise that it's not a good idea to change the expressions in this way. At most, we can align up to the hour level, but nothing more. The user can create a lot of complicated expressions through the UI, and we can't just throw them over the top just to be able to always run at the specified start time.

**Comment by lippserd** [comment]
> After a long time of experimenting, I finally realise that it's not a good idea to change the expressions in this way. At most, we can align up to the hour level, but nothing more. The user can create a lot of complicated expressions through the UI, and we can't just throw them over the top just to be able to always run at the specified start time.

How is something like this supposed to work?

```php
$now = new DateTime(); // Showcase for every other day than sunday
$weekly = new Cron('@weekly');
$weekly->startAt($now);
var_dump(
    (clone $now)->modify('+1 week'),
    $weekly->getNextDue($now)
);
assert((clone $now)->modify('+1 week') === $weekly->getNextDue($now));
```

Sure, `@weekly` defaults to Sunday but I don't see a reason to not support something like that.

**Comment by yhabteab** [comment]
We already have a special handling for the start time when it's defined, i.e. the expression can never be due before the specified start time. However, if you insist on the expression always being executed at the specified start time, then we could do this for the **aliased expressions**, though not for all the others. Because that would break apart what you have built via the UI.

Side note: Your assertion from above basically would never work regardless of whether we're aligning or not, since the Cron library drops `seconds`, `milliseconds` etc..

**Comment by lippserd** [comment]
I'm ok with not automagically modifying the expression. You can close PR and delete the branch.

**Pull request closed without merging**
